### ISSUE TITLE
Flask-Cache: CACHE_TYPE is set to null

### ISSUE THREAD

**Issue by johnarnold** [vimeo/graphite-influxdb#30]
Using the docker image, it's like it's not respecting the cache config in /etc/graphite-api.yaml.

I've tried a bunch of things, currently looks like:

cache:
    # memcache seems to have issues with storing the series. the data is too big and doesn't store it, and doesn't allow bumping size in config that much
    #CACHE_TYPE: 'memcached'
    #CACHE_KEY_PREFIX: 'graphite_api'
    type: 'filesystem'
    dir: '/tmp/graphite-api-cache'
    #CACHE_TYPE: 'filesystem'
    #CACHE_DIR: '/tmp/graphite-api-cache'

root@764a462ddbf4:/etc# cat /var/log/graphite-api.log
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
/usr/local/lib/python2.7/dist-packages/flask_cache/**init**.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
{"index_path": "/srv/graphite/index", "event": "reading index data"}
{"index_path": "/srv/graphite/index", "duration": 5.2928924560546875e-05, "total_entries": 0, "event": "search index reloaded"}
{"path": "/etc/graphite-api.yaml", "event": "loading configuration"}
/usr/local/lib/python2.7/dist-packages/flask_cache/**init**.py:152: UserWarning: Flask-Cache: CACHE_TYPE is set to null, caching is effectively disabled.
  warnings.warn("Flask-Cache: CACHE_TYPE is set to null, "
{"index_path": "/srv/graphite/index", "event": "reading index data"}
{"index_path": "/srv/graphite/index", "duration": 5.412101745605469e-05, "total_entries": 0, "event": "search index reloaded"}

**Comment by r3cgm** [comment]
I'm getting the exact same situation as johnarnold, where the service only stays up and stable on a restart.  Otherwise get a:

...
File "/usr/lib/python2.7/os.py", line 157, in makedirs
mkdir(name, mode)
OSError: [Errno 17] File exists: '/tmp/graphite-api-cache'

Any idea how to make it come up successfully the first time?

I'm hoping I don't come back here in a couple minutes reporting the "not getting data" problem too. :)

**Comment by r3cgm** [comment]
As it turns out the data came right in.  So aside from the need to restart gunicorn every time the docker container spawns, everything else seems to be working correctly.
