### ISSUE TITLE
latest influxdb.InfluxDBClient  and influxDB 0.8.8

### ISSUE THREAD

**Issue by vaclavrak** [vimeo/graphite-influxdb#44]
Hi all, nice work, for while I fight with influxdb installed via PIP. I was not able to make it work until I found problem with influxdb lib, what have compatibility update
so I changed line 6
```python 

from influxdb import InfluxDBClient
```
to 

```python 
from influxdb.influxdb08  import InfluxDBClient
```

woala all is working now :) 
```bash
# pip list | grep influx
graphite-influxdb (0.4)
influxdb (1.0.0)
```

**Comment by mnuessler** [comment]
I ran into the same problem. Since InfluxDB 0.9 is not yet supported, wouldn't it make sense to update the import accordingly?

**Comment by Dieterbe** [comment]
could you file a PR?
